"""
PostgreSQL DDL skeleton + data migration from SQLite.

Usage:
  python scripts/migrate_to_postgres.py --ddl-only    # print DDL, no DB connection needed
  python scripts/migrate_to_postgres.py               # requires DATABASE_URL in .env

DO NOT RUN the full migration without Rahul's explicit approval:
  - The UPDATE statements below reassign all 'user_1' rows to Rahul's real Supabase UUID.
  - Run --ddl-only first to review, then get approval before executing.
"""
from __future__ import annotations
import os
import sys
import argparse
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

# ---------------------------------------------------------------------------
# PostgreSQL DDL — translate from SQLite types
# ---------------------------------------------------------------------------

DDL = """
-- ============================================================
-- Nyaya Recall — PostgreSQL schema
-- Generated by scripts/migrate_to_postgres.py
-- Run on Railway PostgreSQL (same project as Nyaya Scribe).
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()

-- User profiles (source of truth: Supabase auth.users)
CREATE TABLE IF NOT EXISTS user_profiles (
    user_id      TEXT PRIMARY KEY,           -- Supabase UUID (auth.users.id)
    display_name TEXT,
    email        TEXT,
    exam_type    TEXT    NOT NULL DEFAULT 'upsc_prelims',
    target_date  DATE,
    daily_hours  REAL    NOT NULL DEFAULT 2.0,
    tier         TEXT    NOT NULL DEFAULT 'free',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Quiz sessions
CREATE TABLE IF NOT EXISTS quiz_sessions (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES user_profiles(user_id),
    subject_id   TEXT,
    topic_id     TEXT,
    subtopic_id  TEXT,
    mode         TEXT,
    config       TEXT,
    start_time   TIMESTAMPTZ,
    end_time     TIMESTAMPTZ,
    synced       INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_qs_user    ON quiz_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_qs_synced  ON quiz_sessions(user_id, synced);

-- Session answers
CREATE TABLE IF NOT EXISTS session_answers (
    id              SERIAL PRIMARY KEY,
    session_id      TEXT NOT NULL REFERENCES quiz_sessions(id),
    user_id         TEXT NOT NULL,
    subject_id      TEXT,
    topic_id        TEXT,
    subtopic_id     TEXT,
    dimension_id    TEXT,
    question_text   TEXT,
    question_hash   TEXT,
    options         TEXT,
    correct_answer  TEXT,
    user_answer     TEXT,
    is_correct      INTEGER,
    skipped         INTEGER NOT NULL DEFAULT 0,
    time_taken_sec  INTEGER,
    concept_expanded INTEGER NOT NULL DEFAULT 0,
    UNIQUE(session_id, question_hash)
);
CREATE INDEX IF NOT EXISTS idx_sa_session   ON session_answers(session_id);
CREATE INDEX IF NOT EXISTS idx_sa_user      ON session_answers(user_id);
CREATE INDEX IF NOT EXISTS idx_sa_subtopic  ON session_answers(user_id, subtopic_id);

-- Session summaries
CREATE TABLE IF NOT EXISTS session_summaries (
    session_id          TEXT PRIMARY KEY REFERENCES quiz_sessions(id),
    user_id             TEXT NOT NULL,
    subject_id          TEXT,
    session_date        TEXT,
    total_questions     INTEGER,
    correct             INTEGER,
    accuracy_pct        REAL,
    weak_subtopics      TEXT,
    strong_subtopics    TEXT,
    expanded_subtopics  TEXT,
    note                TEXT
);

-- Subtopic scores (running accuracy per user × subtopic)
CREATE TABLE IF NOT EXISTS subtopic_scores (
    id              SERIAL PRIMARY KEY,
    user_id         TEXT NOT NULL,
    subject_id      TEXT NOT NULL,
    topic_id        TEXT,
    subtopic_id     TEXT NOT NULL,
    score           REAL NOT NULL DEFAULT 0.0,
    total_attempts  INTEGER NOT NULL DEFAULT 0,
    last_tested     TIMESTAMPTZ,
    UNIQUE(user_id, subject_id, topic_id, subtopic_id)
);
CREATE INDEX IF NOT EXISTS idx_ss_user ON subtopic_scores(user_id);

-- Subtopic dimension scores (per-dimension accuracy)
CREATE TABLE IF NOT EXISTS subtopic_dimension_scores (
    id           SERIAL PRIMARY KEY,
    user_id      TEXT NOT NULL,
    subject_id   TEXT NOT NULL,
    subtopic_id  TEXT NOT NULL,
    dimension_id TEXT NOT NULL,
    score        REAL NOT NULL DEFAULT 0.0,
    attempts     INTEGER NOT NULL DEFAULT 0,
    last_tested  TIMESTAMPTZ,
    UNIQUE(user_id, subject_id, subtopic_id, dimension_id)
);

-- Self-attestation reliability scores
-- NOTE: PRIMARY KEY changed from user_id (broken for multi-user) → id SERIAL
-- ⚠️  Requires ALTER TABLE sar_scores on existing SQLite DB before migration.
CREATE TABLE IF NOT EXISTS sar_scores (
    id          SERIAL PRIMARY KEY,
    user_id     TEXT NOT NULL UNIQUE,
    sar_score   REAL NOT NULL DEFAULT 0.5,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Per-quiz-session subtopics (multi-subtopic sessions)
CREATE TABLE IF NOT EXISTS quiz_session_subtopics (
    id          SERIAL PRIMARY KEY,
    session_id  TEXT NOT NULL REFERENCES quiz_sessions(id),
    subtopic_id TEXT NOT NULL,
    subject_id  TEXT,
    topic_id    TEXT,
    q_allocated INTEGER NOT NULL DEFAULT 0
);

-- Exam simulation history
CREATE TABLE IF NOT EXISTS exam_sim_history (
    id              SERIAL PRIMARY KEY,
    user_id         TEXT NOT NULL,
    session_id      TEXT NOT NULL REFERENCES quiz_sessions(id),
    subject_ids     TEXT,
    total_questions INTEGER,
    correct         INTEGER,
    accuracy_pct    REAL,
    duration_sec    INTEGER,
    completed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Session-level user notes (legacy — kept for backward compat)
CREATE TABLE IF NOT EXISTS session_user_notes (
    session_id               TEXT PRIMARY KEY REFERENCES quiz_sessions(id),
    user_id                  TEXT NOT NULL,
    subject_id               TEXT,
    subtopic_id              TEXT NOT NULL,
    confusion                TEXT DEFAULT '',
    mnemonic                 TEXT DEFAULT '',
    still_weak               INTEGER NOT NULL DEFAULT 0,
    question_context_index   INTEGER,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Per-question notes (ISSUE-017)
CREATE TABLE IF NOT EXISTS question_notes (
    id              SERIAL PRIMARY KEY,
    user_id         TEXT NOT NULL,
    session_id      TEXT NOT NULL REFERENCES quiz_sessions(id),
    question_hash   TEXT NOT NULL,
    question_index  INTEGER NOT NULL,
    subtopic_id     TEXT NOT NULL,
    subject_id      TEXT NOT NULL,
    note_text       TEXT DEFAULT '',
    still_weak      INTEGER NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(session_id, question_hash)
);
CREATE INDEX IF NOT EXISTS idx_qn_user    ON question_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_qn_subtopic ON question_notes(subtopic_id, still_weak);

-- Content feedback (ISSUE-017)
CREATE TABLE IF NOT EXISTS content_feedback (
    id            SERIAL PRIMARY KEY,
    user_id       TEXT NOT NULL,
    content_type  TEXT NOT NULL,
    session_id    TEXT NOT NULL,
    question_hash TEXT,
    subtopic_id   TEXT NOT NULL,
    subject_id    TEXT NOT NULL,
    notes_section TEXT,
    verdict       TEXT NOT NULL,
    note_text     TEXT DEFAULT '',
    prompt_file   TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cf_subtopic ON content_feedback(subtopic_id, content_type);
CREATE INDEX IF NOT EXISTS idx_cf_prompt   ON content_feedback(prompt_file, verdict);

-- Plan edit log (tracks what user changed vs AI-generated plan)
CREATE TABLE IF NOT EXISTS plan_edit_log (
    id               SERIAL PRIMARY KEY,
    user_id          TEXT NOT NULL DEFAULT 'user_1',
    session_date     TEXT NOT NULL,
    session_index    INTEGER NOT NULL,
    original_session TEXT NOT NULL,
    edited_session   TEXT NOT NULL,
    edit_timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    changed_fields   TEXT
);

-- PYQ questions (shared across all users — no user_id)
CREATE TABLE IF NOT EXISTS pyq_questions (
    id              SERIAL PRIMARY KEY,
    year            INTEGER,
    q_number        INTEGER,
    subject_id      TEXT,
    topic_id        TEXT,
    subtopic_id     TEXT,
    question_text   TEXT,
    options         TEXT,
    correct_answer  TEXT,
    answer_source   TEXT DEFAULT 'ai_inferred',
    answer_disputed INTEGER NOT NULL DEFAULT 0,
    dispute_note    TEXT,
    difficulty      TEXT,
    dimension_id    TEXT,
    source_file     TEXT,
    ingested_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pyq_year    ON pyq_questions(year);
CREATE INDEX IF NOT EXISTS idx_pyq_subject ON pyq_questions(subject_id, subtopic_id);
"""

# ---------------------------------------------------------------------------
# Data migration — DO NOT RUN without Rahul's explicit approval
# Swap 'user_1' → '<rahul_supabase_uuid>' in all tables.
# Get UUID from: Supabase Dashboard → Authentication → Users → copy UUID
# ---------------------------------------------------------------------------

MIGRATION_SQL_TEMPLATE = """
-- ⚠️  APPROVAL REQUIRED before running this block.
-- Replace <RAHUL_UUID> with Rahul's actual Supabase UUID before executing.

DO $$
DECLARE
    rahul_uuid TEXT := '<RAHUL_UUID>';
BEGIN
    -- Seed user_profiles for Rahul
    INSERT INTO user_profiles (user_id, display_name, exam_type, tier)
    VALUES (rahul_uuid, 'Rahul', 'upsc_prelims', 'free')
    ON CONFLICT (user_id) DO NOTHING;

    -- Migrate all tables
    UPDATE quiz_sessions           SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE session_answers         SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE session_summaries       SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE subtopic_scores         SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE subtopic_dimension_scores SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE sar_scores              SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE exam_sim_history        SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE session_user_notes      SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE question_notes          SET user_id = rahul_uuid WHERE user_id = 'user_1';
    UPDATE content_feedback        SET user_id = rahul_uuid WHERE user_id = 'user_1';
END $$;
"""


def main():
    parser = argparse.ArgumentParser(description="PostgreSQL DDL + migration for Nyaya Recall")
    parser.add_argument("--ddl-only", action="store_true",
                        help="Print DDL without connecting to any database")
    parser.add_argument("--show-migration", action="store_true",
                        help="Print the data migration SQL template (requires manual UUID substitution)")
    args = parser.parse_args()

    if args.ddl_only:
        print(DDL)
        return

    if args.show_migration:
        print(MIGRATION_SQL_TEMPLATE)
        return

    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        print("ERROR: DATABASE_URL not set in .env — cannot connect to PostgreSQL.")
        print("Use --ddl-only to print DDL without a DB connection.")
        sys.exit(1)

    try:
        import psycopg2
    except ImportError:
        print("ERROR: psycopg2 not installed. Run: pip install psycopg2-binary")
        sys.exit(1)

    print(f"Connecting to PostgreSQL...")
    conn = psycopg2.connect(database_url)
    conn.autocommit = False
    cur = conn.cursor()

    try:
        print("Running DDL (CREATE TABLE IF NOT EXISTS — safe to re-run)...")
        cur.execute(DDL)
        conn.commit()
        print("✅ DDL applied successfully.")
        print()
        print("Next step (requires Rahul approval):")
        print("  Run --show-migration to see the data migration SQL.")
        print("  Substitute <RAHUL_UUID> with real UUID, then execute manually in psql.")
    except Exception as e:
        conn.rollback()
        print(f"ERROR: {e}")
        sys.exit(1)
    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    main()
