"""
One-time script: re-classifies PYQ question subtopic_id values to canonical
syllabus IDs.

WHY THIS EXISTS
---------------
PYQ questions were ingested with free-text subtopic descriptors generated by
Claude (e.g. ``directive_principles``, ``rbi_operations``).  These do NOT match
the 205 canonical subtopic IDs in ``data/syllabus.json``.

``scripts/priority_scorer.py`` now contains a fuzzy-match fallback that covers
~30 % of questions.  Running THIS script upgrades coverage to ~100 % by asking
Claude Haiku to classify each question against the relevant syllabus subtopic
list and updating the DB in-place.

COST ESTIMATE
-------------
~1069 questions, batched by subject (10 subjects × ~107 Qs each).
Each batch = ~1 000–2 000 input tokens + ~500 output tokens using Haiku.
Estimated total: ~$0.04–0.06 at Haiku pricing.

RUN ONCE ONLY
-------------
After running, the fuzzy-match fallback in priority_scorer.py becomes a no-op
because all subtopic_ids will be canonical syllabus IDs.

Usage (from project root):
    python3 scripts/retag_pyq_subtopics.py

    # Dry-run (see proposed changes, no DB writes):
    python3 scripts/retag_pyq_subtopics.py --dry-run
"""
from __future__ import annotations
import argparse
import json
import os
import sqlite3
import sys
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")

DB_PATH = os.getenv("DB_PATH", "data/upsc.db")
SYLLABUS_PATH = (
    Path(os.getenv("PROJECT_PATH", str(Path(__file__).parent.parent)))
    / "data"
    / "syllabus.json"
)

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_syllabus() -> dict[str, list[str]]:
    """Returns {subject_id: [subtopic_id, ...]}."""
    syllabus = json.loads(SYLLABUS_PATH.read_text())
    result: dict[str, list[str]] = {}
    for subj in syllabus.get("subjects", []):
        sids = [
            st["id"]
            for topic in subj.get("topics", [])
            for st in topic.get("subtopics", [])
        ]
        result[subj["id"]] = sids
    return result


def classify_batch(
    questions: list[dict],
    candidate_ids: list[str],
    subject_id: str,
) -> dict[int, str]:
    """Ask Haiku to classify a batch of questions into canonical subtopic IDs.

    Returns {question_id: canonical_subtopic_id}.
    """
    q_lines = "\n".join(
        f"{i+1}. [id={q['id']}] {q['question_text'][:200]}"
        for i, q in enumerate(questions)
    )
    ids_str = "\n".join(f"  - {sid}" for sid in candidate_ids)

    prompt = f"""You are classifying UPSC Prelims questions by subtopic.

Subject: {subject_id}

Available subtopic IDs (ONLY use IDs from this list):
{ids_str}

Questions to classify:
{q_lines}

For each question, respond with exactly:
<id>: <subtopic_id>

where <id> is the numeric question id shown in brackets and <subtopic_id> is one
of the candidate IDs above.  Output ONLY these lines, nothing else."""

    msg = client.messages.create(
        model="claude-haiku-4-5",
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )
    text = msg.content[0].text.strip()

    result: dict[int, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if ":" not in line:
            continue
        parts = line.split(":", 1)
        try:
            qid = int(parts[0].strip())
            subtopic = parts[1].strip()
            if subtopic in candidate_ids:
                result[qid] = subtopic
        except (ValueError, IndexError):
            continue
    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(dry_run: bool = False) -> None:
    syllabus_map = load_syllabus()
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row

    rows = con.execute(
        "SELECT id, subtopic_id, subject_id, question_text FROM pyq_questions "
        "WHERE subtopic_id IS NOT NULL"
    ).fetchall()

    # Group by subject_id
    by_subject: dict[str, list[dict]] = {}
    for row in rows:
        sid = row["subject_id"] or "unknown"
        by_subject.setdefault(sid, []).append(dict(row))

    total_updated = 0
    total_skipped = 0

    for subject_id, questions in by_subject.items():
        candidates = syllabus_map.get(subject_id)
        if not candidates:
            print(f"[SKIP] {subject_id}: no syllabus subtopics found, skipping {len(questions)} Qs")
            total_skipped += len(questions)
            continue

        print(f"[{subject_id}] Classifying {len(questions)} questions → {len(candidates)} candidates …")

        # Batch in chunks of 50 to stay well within context limits
        BATCH = 50
        mapping: dict[int, str] = {}
        for i in range(0, len(questions), BATCH):
            chunk = questions[i : i + BATCH]
            result = classify_batch(chunk, candidates, subject_id)
            mapping.update(result)
            print(f"  batch {i//BATCH + 1}: classified {len(result)}/{len(chunk)}")

        # Apply updates
        updated = 0
        for q in questions:
            new_id = mapping.get(q["id"])
            if new_id and new_id != q["subtopic_id"]:
                if dry_run:
                    print(f"  DRY-RUN: id={q['id']} {q['subtopic_id']!r} → {new_id!r}")
                else:
                    con.execute(
                        "UPDATE pyq_questions SET subtopic_id = ? WHERE id = ?",
                        (new_id, q["id"]),
                    )
                updated += 1
        total_updated += updated
        print(f"  → {updated}/{len(questions)} updated")

    if not dry_run:
        con.commit()
        print(f"\nDone. {total_updated} rows updated, {total_skipped} skipped.")
        print("Run priority_scorer.py next to recompute weights.")
    else:
        print(f"\nDry-run complete. {total_updated} rows would be updated, {total_skipped} skipped.")

    con.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Re-classify PYQ subtopic IDs to canonical syllabus IDs.")
    parser.add_argument("--dry-run", action="store_true", help="Show changes without writing to DB.")
    args = parser.parse_args()
    main(dry_run=args.dry_run)
